services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flights_api
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - app-network
    env_file:
      - .env

volumes:
  mongodb_data:


networks:
  app-network:
    driver: bridge